### ISSUE TITLE
[BUG] Indexing Job Keeps Running For Hours

### ISSUE THREAD

**Issue by mohanajuhi166** [Azure-Samples/graphrag-accelerator#91] opened 2024-07-16 10:05 UTC
**Describe the bug**
 Indexing Job Keeps Running For Hours and Ultimately fails in SwedenCentral Location

**To Reproduce**
1. Setup up OpenAI Studio with gpt-4 and open-ai-embeddings
2.Setup up TPM thresholds as per documentation
3. Build Index in swedencentral region

**Expected behavior**
Indexing Job Finishes

**Screenshots**

This is where it gets stuck, at 12.5% and remains the same for the next 3-4hrs 
<img width="560" alt="Screenshot 2024-07-16 at 12 04 48" src="https://github.com/user-attachments/assets/9809d639-9f41-4e8f-8929-8a67e13f15b8">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: Latest

**Comment by MemmoB** [comment] 2024-07-19 11:06
I get this when indexing 3 wiki pages as a test:
```
{
  "status_code": 200,
  "index_name": "graphrag-test",
  "storage_name": "graphrag-test",
  "status": "failed",
  "percent_complete": 12.5,
  "progress": "2 out of 16 workflows completed successfully."
}

```
And then it restarts and never gets passed this point and restarts again etc.

**Comment by MemmoB** [comment] 2024-07-19 11:08
Duplicate of https://github.com/Azure-Samples/graphrag-accelerator/issues/55

**Comment by rnpramasamyai** [comment] 2024-07-23 07:44
Same Here

**Comment by rnpramasamyai** [comment] 2024-07-31 03:00
Please check whether pods are crashing in AKS and review the pod logs.

**Comment by zhangchuang1128** [comment] 2024-08-05 06:39
Same Here，Have you solved this problem？

**Comment by timothymeyers** [comment] 2024-08-05 14:16
Closing as a duplicate; please see discussion in #55 for troubleshooting approaches. 

If new errors show in deployment or pod logs, please open a new issue with greater detail and context.

**Closed by timothymeyers** 2024-08-05 14:16 UTC
Labels: bug
