### ISSUE TITLE
[BUG]existing container registry leads to deploy.sh failed

### ISSUE THREAD

**Issue by jorgelunams** [Azure-Samples/graphrag-accelerator#104] opened 2024-07-25 15:12 UTC
**Describe the bug**
The script to deploy deploy.parameters.json the accelerator failed with error.

**To Reproduce** 
$ bash deploy.sh -p deploy.parameters.json 

**Expected behavior**
45 minutes to deploy
**Screenshots**
Checking for required tools... Done.
Checking required parameters... Done.
Checking optional parameters...
        setting AISEARCH_ENDPOINT_SUFFIX=search.windows.net
        setting AISEARCH_AUDIENCE=https://search.azure.com
        setting PUBLISHER_NAME=publisher
        setting PUBLISHER_EMAIL=publisher@microsoft.com
        setting CONTAINER_REGISTRY_EMAIL=publisher@microsoft.com
        setting CLOUD_NAME=AzurePublicCloud
        setting REPORTERS=blob,console,app_insights
        setting GRAPHRAG_COGNITIVE_SERVICES_ENDPOINT=https://cognitiveservices.azure.com/.default
        setting GRAPHRAG_IMAGE=graphrag:backend
Done.
Checking if resource group graphraggroup exists... Yes.
Checking if container registry exists... No.
Creating container registry... 'cr2dfbi4hcyv57u.azurecr.io' created.
Deploying docker image 'graphrag:backend' to container registry 'cr2dfbi4hcyv57u.azurecr.io'...Error deploying docker image, exiting...

ERROE ABOVE 

**Desktop (please complete the following information):**

**Additional context**
All is created failes at the end.

**Comment by timothymeyers** [comment] 2024-07-25 20:21
Hey @jorgelunams I assume you saw #87 given the same title. Have you pulled the latest and tried that?

I just did a fresh deployment with #88 merged and am not seeing this error anymore.

**Comment by timothymeyers** [comment] 2024-07-25 20:27
I'm going to close this as a duplicate of #87; let's keep the discussion over there if it is still an issue. Thanks!

**Closed by timothymeyers** 2024-07-25 20:27 UTC
Labels: bug, duplicate

**Comment by jorgelunams** [comment] 2024-07-25 23:36
Hi Tomothy, the problem is still there. I am sure something we are doing wrong. Do you work for Microsoft? I could not find you.
